name: Release

# manual only kick off
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest 

    steps:
      
      - name: â¬‡ï¸ Download artifacts from latest workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

      - name: ðŸ” view artifacts to be used
        run: ls -R
        working-directory: .

      - name: ðŸ”¢ set version environment variable
        run: |
          echo "VERSION=$(cat bin/version.txt)" >> "$GITHUB_ENV"

      - name: ðŸ”¢ prep release notes
        run: |
          grep -m 2 -B 1000 '^## ' bin/release-notes.md | tail -n +3 | head -n -2 > final_notes.md
          cat bin/instructions.md >> final_notes.md
          echo "$\n$\nSHA-256 checksums:$\n```" >> final_notes.md
          sha256sum bt-* >> final_notes.md
          echo "```" >> final_notes.md
          cat final_notes.md
          

      # https://github.com/softprops/action-gh-release
      - name: ðŸ“¦ create release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          files: |
            bin/*.msi
            bin/*.zip
          body_path: final_notes.md
